# Generated by Django 3.2.4 on 2021-06-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieratings',
            name='created',
        ),
        migrations.RemoveField(
            model_name='movieratings',
            name='modified',
        ),
    ]
