# Generated by Django 3.2.4 on 2021-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20210605_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieratings',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
