# Generated by Django 3.2.4 on 2021-06-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
