# Generated by Django 3.2.4 on 2021-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieratings',
            name='release_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
